repos:
  - repo: https://github.com/mineiros-io/pre-commit-hooks
    rev: v0.5.0
    hooks:
      - id: terramate-fmt
      - id: terramate-generate
      - id: terraform-fmt
      - id: terradoc-fmt
      - id: terradoc-generate
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        exclude: ^(.*).md$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint
        args: ['-s']
