name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
concurrency:
  group: terraform-google-iam
  cancel-in-progress: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - name: Checkout
        # for security reasons we pin commit ids and not tags.
        # actions/checkout@v3.0.2 -> 2541b1294d2704b0964813337f33b291d3f8596b
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: Setup asdf
        # asdf-vm/actions/plugins-add@v2.1.0 = 83133f03f5693901c2296a8e622955087dc20267
        uses: asdf-vm/actions/plugins-add@83133f03f5693901c2296a8e622955087dc20267

      - name: Install tools via asdf
        run: asdf install

      - name: Set up Golang
        # for security reasons we pin commit ids and not tags.
        # actions/setup-go@v3.5.0 -> 6edd4406fa81c3da01a34fa6f6343087c207a568
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: 1.18.7

      - name: Set up Terradoc
        # for security reasons we pin commit ids and not tags.
        # mineiros-io/terradoc@main -> 018bd4ae81f5dd901cc5a76f34e6acb362b2110e
        run: |
          go install github.com/mineiros-io/terradoc/cmd/terradoc@018bd4ae81f5dd901cc5a76f34e6acb362b2110e
        env:
          GOPROXY: direct

      - name: Run pre-commit
        run: make test/pre-commit/all

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Checkout
        # for security reasons we pin commit ids and not tags.
        # actions/checkout@v3.0.2 -> 2541b1294d2704b0964813337f33b291d3f8596b
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: Setup asdf
        # asdf-vm/actions/plugins-add@v2.1.0 = 83133f03f5693901c2296a8e622955087dc20267
        uses: asdf-vm/actions/plugins-add@83133f03f5693901c2296a8e622955087dc20267

      - name: Install tools via asdf
        run: asdf install

      - name: Run Unit Tests
        run: make test/unit-tests
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.MINEIROS_TESTING_GCP_SA_KEY_FILE }}
          TEST_GCP_PROJECT: ${{ secrets.MINEIROS_TESTING_GCP_PROJECT }}
          TEST_GCP_ORG_DOMAIN: ${{ secrets.MINEIROS_TESTING_GCP_ORG_DOMAIN }}
