name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - run: true

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - run: true
