name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
concurrency:
  group: terraform-google-iam
  cancel-in-progress: false

env:
  static_analysis_tools: terraform terramate tflint pre-commit
  unit_tests_tools: terraform terramate golang

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - name: Checkout
        # for security reasons we pin commit ids and not tags.
        # actions/checkout@v3.0.2 -> 2541b1294d2704b0964813337f33b291d3f8596b
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: Setup asdf
        # asdf-vm/actions/plugins-add@v2.1.0 = 83133f03f5693901c2296a8e622955087dc20267
        uses: asdf-vm/actions/plugins-add@83133f03f5693901c2296a8e622955087dc20267

      - name: Install selected tools via asdf
        run: for i in $static_analysis_tools ; do asdf install $i ; done

      # - name: Set up Terradoc
      #   # for security reasons we pin commit ids and not tags.
      #   # mineiros-io/terradoc@main -> af1a7b3ae3635958adf5ee2f40e0c3e70fd0803a
      #   run: go install github.com/mineiros-io/terradoc/cmd/terradoc@af1a7b3ae3635958adf5ee2f40e0c3e70fd0803a
      #   env:
      #     GOPROXY: direct

      - name: Run pre-commit
        run: make test/pre-commit

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Checkout
        # for security reasons we pin commit ids and not tags.
        # actions/checkout@v3.0.2 -> 2541b1294d2704b0964813337f33b291d3f8596b
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0

      - name: Setup asdf
        # asdf-vm/actions/plugins-add@v2.1.0 = 83133f03f5693901c2296a8e622955087dc20267
        uses: asdf-vm/actions/plugins-add@83133f03f5693901c2296a8e622955087dc20267

      - name: Install selected tools via asdf
        run: for i in $unit_tests_tools ; do asdf install $i ; done

      - name: Ensure test assets are up to date
        run: make test/update-assets

      - name: Run Unit Tests
        run: make test/unit-tests
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.MINEIROS_TESTING_GCP_SA_KEY_FILE }}
          TEST_GCP_PROJECT: ${{ secrets.MINEIROS_TESTING_GCP_PROJECT }}
          TEST_GCP_ORG_DOMAIN: ${{ secrets.MINEIROS_TESTING_GCP_ORG_DOMAIN }}
